version: '3'
services:
  a_stock:
    image: hyeongjin0319/stock-trade:latest
    container_name: a_stock
    hostname: a_stock
    ports:
      - 8080:8080
    restart: always
    environment:
      KIS_APP_KEY: ${KIS_APP_KEY}
      KIS_APP_SECRET: ${KIS_APP_SECRET}
      CANO: ${CANO}
      ACNT_PRDT_CD: ${ACNT_PRDT_CD}
      KIS_API_BASE: ${KIS_API_BASE}
      SYMBOL_LIST: ${SYMBOL_LIST}
      NASD_SYMBOL_LIST: ${NASD_SYMBOL_LIST}
      NYSE_SYMBOL_LIST: ${NYSE_SYMBOL_LIST}
      AMEX_SYMBOL_LIST: ${AMEX_SYMBOL_LIST}
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      LOG_DATE: ${LOG_DATE}
      BASIC_LOG_LEVEL: ${BASIC_LOG_LEVEL}
      NATION: ${NATION}
      STDOUT_LOGGER_USE_YN: ${STDOUT_LOGGER_USE_YN}
    depends_on:
      - redis

  redis: # container name
    container_name: redis
    image: redis:latest
    hostname: a_stock_redis
    ports: # 바인딩할 포트:내부 포트
      - ${REDIS_BINDING_PORT}:${REDIS_PORT}
    command: redis-server --port ${REDIS_PORT}
    restart: always